# Generated by Django 4.0.2 on 2022-02-13 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('home', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='src.folder')),
            ],
        ),
        migrations.AddField(
            model_name='folder',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='src.user'),
        ),
        migrations.AddField(
            model_name='folder',
            name='folder',
            field=models.ManyToManyField(related_name='parent', to='src.Folder'),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('extension', models.CharField(max_length=12)),
                ('link', models.CharField(max_length=70)),
                ('document', models.FileField(null=True, upload_to='files')),
                ('doc_name', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='src.user')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Documents', to='src.folder')),
            ],
        ),
    ]
